[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib", "lib"]  # rlib은 테스트, 벤치마크 용

[dependencies]
flutter_rust_bridge = "1"
